compiler:
  - clang
  - gcc
before_script:
  - sudo apt-get update
  - sudo apt-get install libeigen3-dev
  - sudo apt-get install cython
  - sudo apt-get install python-numpy
  - sudo apt-get install libqt4-dev
  - sudo apt-get install libxmu-dev
  - sudo apt-get install freeglut3
  - sudo apt-get install libqt4-opengl-dev
script:
  - mkdir build
  - cd build
  - cmake ..
  - make
notifications:
  recipients:
    - afabisch@informatik.uni-bremen.de
  email:
    on_success: change
    on_failure: always
