compiler:
  - clang
  - gcc
before_script: sudo apt-get install libeigen3-dev
script:
  - mkdir build
  - cd build
  - cmake ..
  - make
notifications:
  recipients:
    - afabisch@informatik.uni-bremen.de
  email:
    on_success: change
    on_failure: always
